# Generate edge device configuration file after apply
# Copy the output file to your edge device at ooda/edge/upload/.env

resource "local_file" "edge_env" {
  filename = "${path.module}/../../ooda/edge/upload/.env.generated"

  content = <<-EOT
# Auto-generated by Terraform — do not edit manually
# Copy this file to the edge device as .env

# AWS region
AWS_DEFAULT_REGION=${var.aws_region}

# S3 configuration
OODA_S3_BUCKET=${var.enable_upload ? module.upload[0].bucket_name : ""}
OODA_S3_REGION=${var.aws_region}

# Storage configuration
OODA_MAX_BUFFER_SIZE_GB=5

# Logging
OODA_LOG_LEVEL=INFO

# Upload schedule
OODA_UPLOAD_INTERVAL_HOURS=1

# Compression
OODA_COMPRESSION_ENABLED=true
OODA_COMPRESSION_CRF=28

# Batching
OODA_BATCHING_ENABLED=true
OODA_BATCH_WINDOW_HOURS=1

# IoT configuration
OODA_IOT_ENDPOINT=${var.enable_iot ? data.aws_iot_endpoint.iot.endpoint_address : ""}
OODA_IOT_THING_NAME=${var.enable_iot ? aws_iot_thing.edge_thing[0].name : ""}
EOT
}

resource "local_sensitive_file" "edge_iot_certificate" {
  count    = var.enable_iot ? 1 : 0
  filename = "${path.module}/../../ooda/edge/certs/iot_certificate.pem"
  content  = tls_self_signed_cert.edge_cert[0].cert_pem
}

resource "local_sensitive_file" "edge_iot_private_key" {
  count    = var.enable_iot ? 1 : 0
  filename = "${path.module}/../../ooda/edge/certs/iot_private_key.pem"
  content  = tls_private_key.edge_key[0].private_key_pem
}
